### ISSUE TITLE
Chat list not found

### ISSUE THREAD

**Issue by tocha699** [eilvelia/tdl#177]
TDLibError: Chat list not found
    at Client._handleReceive (C:\Codes\tdl-node-test\node_modules\.pnpm\tdl@8.0.1\node_modules\tdl\dist\client.js:532:30)
    at Client.handleReceive (C:\Codes\tdl-node-test\node_modules\.pnpm\tdl@8.0.1\node_modules\tdl\dist\client.js:513:18)
    at receiveLoop (C:\Codes\tdl-node-test\node_modules\.pnpm\tdl@8.0.1\node_modules\tdl\dist\index.js:139:20) {
  _: 'error',
  code: 400
}

```
const chats2 = await client.invoke({ _: "loadChats" }).catch(e => {
    console.log(e)
  })
```

**Comment by eilvelia** [comment]
Try to use `{ _: 'loadChats', chat_list: { _: 'chatListMain' }, limit: 100 }`. Also the chats will be returned as an update, not as the response.
