### ISSUE TITLE
 TypeError: null is not an object (evaluating 'l.type')

### ISSUE THREAD

**Issue by T1MOXA** [eilvelia/tdl#180]
Runtime: `BunJS 1.1.37`
Lib Version: `8.0.1`
OS Version: `Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-50-generic x86_64)`
prebuilt-tdlib: `0.1008040.0`

```
 236 |                         throw new Error('Invariant violation: loginDetails is null');
 237 |                 }
 238 |                 function needUserLogin(l) {
 239 |                     if (l == null)
 240 |                         needLoginDetails(l);
 241 |                     if (l.type !== 'user')
                               ^
 TypeError: null is not an object (evaluating 'l.type')
       at needUserLogin (/project/node_modules/tdl/dist/client.js:241:25)
       at /project/node_modules/tdl/dist/client.js:326:33
       at processAuthorizationState (/project/node_modules/tdl/dist/client.js:244:58)
       at /project/node_modules/tdl/dist/client.js:390:21
       at new Promise (1:11)
       at /project/node_modules/tdl/dist/client.js:226:20
       at /project/client.js:186:18
```

I tried different variations of `td.login();`
For now it's just `await td.login();`

**Comment by eilvelia** [comment]
This should work if you log in from a clean database (delete the td database directory). Will be fixed in the next release.
